sudo: required

services:
  - docker

before_install:
  - git checkout -qf $TRAVIS_BRANCH
install:
  - docker build -t thegem .

script:
  - docker run -it --rm -e CODECLIMATE_REPO_TOKEN=$CC -v $TRAVIS_BUILD_DIR:/opt/project/code thegem bundle exec rake

deploy:
  provider: rubygems
  api_key: "$RG"
  on:
    branch: master
    tags: true
